application:
  name: app-chart
  namespace: argocd
  source:
    repoURL: https://github.com/nadavcool543/app-chart.git
    targetRevision: HEAD
    path: app-chart
  destination:
    namespace: app-chart

#the value for my app chart
appChart:
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.21.1"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
