apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  project: default
  sources:
    - repoURL: https://github.com/nadavcool543/app-chart.git
      targetRevision: HEAD
      path: .
      helm:
        valueFiles:
          - $values/environment/{{ .Values.environment }}/value.yaml
    - repoURL: https://github.com/nadavcool543/app-chart-infrastructure.git
      targetRevision: HEAD
      path: .
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.application.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
