apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  project: default
  sources:
    - repoURL: {{ .Values.application.source.repoURL }}
      targetRevision: {{ .Values.application.source.targetRevision }}
      path: {{ .Values.application.source.path }}
    - repoURL: https://github.com/nadavcool543/app-chart-infrastructure.git
      targetRevision: HEAD
      path: .
  sourceType: Helm
  helm:
    valueFiles:
      - override-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.application.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
