apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  project: default
  source:
    repoURL: {{ .Values.application.source.repoURL }}
    targetRevision: {{ .Values.application.source.targetRevision }}
    path: {{ .Values.application.source.path }}
    helm:
      values: |
        replicaCount: {{ .Values.appChart.replicaCount }}
        image:
          repository: {{ .Values.appChart.image.repository }}
          tag: {{ .Values.appChart.image.tag | quote }}
          pullPolicy: {{ .Values.appChart.image.pullPolicy }}
        service:
          type: {{ .Values.appChart.service.type }}
          port: {{ .Values.appChart.service.port }}
        {{- with .Values.appChart.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.appChart.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.appChart.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.appChart.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.application.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
